data:
  train_urls:
    - "gs://levanter-dataset-eu/NCC_plus_scandi/train-shard-{0001..0147}-of-0147.json.gz"
  validation_urls:
    - "gs://levanter-dataset-eu/NCC_plus_scandi/validation-shard-0001-of-0001.json.gz"
  cache_dir: "gs://levanter-cache-eu/NCC_plus_scandi/tokenized/llama2verify/"
  tokenizer: "meta-llama/Llama-2-7b-hf"
model:
  type: llama
initialize_from_hf: "meta-llama/Llama-2-7b-hf"
use_hf_model_config: false
trainer:
  wandb:
    entity: "nbailab"
    project: "north-mistral"
    tags: ["llamatoverify"]
    name: north-llamato-verify
  mp: p=f32,c=bfloat16
  train_batch_size: 256  # set for v4-64 TPU
  num_train_steps: 5000
  steps_per_eval: 100
  tensor_parallel_axes: ["mlp", "heads"]
  fsdp_axis: "embed"
  batch_axis: "batch"
  checkpointer:
    base_path: "gs://levanter-checkpoint-eu/north-llama2-verify/checkpoints"
    keep:
      - every: 1000
optimizer:
  learning_rate: 1.2E-5  # set low for fine-tuning
  weight_decay: 0.1
  min_lr_ratio: 0.1
  warmup: 1000
hf_save_steps: 1000
hf_save_path: "gs://levanter-checkpoint-eu/north-llama2-verify/hf"
hf_upload: "north/llama2-verify"
