data:
  train_urls:
    - "gs://pubmed-mosaic/openwebtext-sharded/openwebtext_train.{1..128}-of-128.jsonl.gz"
  validation_urls:
    - "gs://pubmed-mosaic/openwebtext-sharded/openwebtext_val.{1..8}-of-8.jsonl.gz"
  cache_dir: "gs://levanter-cache-eu/tokenized/openwebtext_llama/"
  tokenizer: "mistralai/Mistral-7B-v0.1"
model:
  type: mistral
# TODO: uncomment this once we resolve the resource exhaustion issue
# initialize_from_hf: "mistralai/Mistral-7B-v0.1"
# use_hf_model_config: true
trainer:
  wandb:
    project: "levanter"
    tags: ["openwebtext", "mistral"]

  mp: p=f32,c=bfloat16
  train_batch_size: 128  # set for v4-64 TPU
  num_train_steps: 1000
  steps_per_eval: 250
  tensor_parallel_axes: ["mlp", "heads"]
  fsdp_axis: "embed"
  batch_axis: "batch"
optimizer:
  learning_rate: 1.2E-5  # set low for fine-tuning
  weight_decay: 0.1
  min_lr_ratio: 0.1
